const zoneId = [
    {
        enable: 0,
        mav: false,
        text: '华东1 可用区H',
        value: 'cn-hangzhou-h',
    },
    {
        enable: 0,
        mav: false,
        text: '华南 1 可用区 D',
        value: 'cn-shenzhen-d',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区G',
        value: 'cn-shanghai-g',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 G',
        value: 'cn-beijing-g',
    },
    {
        enable: 0,
        mav: false,
        text: '华南 1 可用区 E',
        value: 'cn-shenzhen-e',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区D+可用区E）',
        value: 'cn-shenzhen-MAZ5(d,e)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区H+可用区I）',
        value: 'cn-hangzhou-MAZ10(h,i)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东1 可用区I',
        value: 'cn-hangzhou-i',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 3 可用区 A',
        value: 'cn-zhangjiakou-a',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 1 可用区 C',
        value: 'cn-qingdao-c',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区G+可用区H）',
        value: 'cn-beijing-MAZ7(g,h)',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 H',
        value: 'cn-beijing-h',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太东南2 可用区A',
        value: 'ap-southeast-2a',
    },
    {
        enable: 0,
        mav: false,
        text: '香港可用区B',
        value: 'cn-hongkong-b',
    },
    {
        enable: 0,
        mav: false,
        text: '欧洲中部1 可用区B',
        value: 'eu-central-1b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'cn-zhangjiakou-MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 3 可用区 B',
        value: 'cn-zhangjiakou-b',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太东南2 可用区B',
        value: 'ap-southeast-2b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'ap-southeast-2MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '美东 1 可用区 A',
        value: 'us-east-1a',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区1（可用区A + 可用区B）',
        value: 'eu-central-1MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '欧洲中部1 可用区A',
        value: 'eu-central-1a',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太东南5 可用区B',
        value: 'ap-southeast-5b',
    },
    {
        enable: 0,
        mav: false,
        text: '伦敦 可用区 B',
        value: 'eu-west-1b',
    },
    {
        enable: 0,
        mav: false,
        text: '华南 1 可用区 A',
        value: 'cn-shenzhen-a',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'ap-southeast-5MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太东南5 可用区A',
        value: 'ap-southeast-5a',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区F＋可用区G）',
        value: 'cn-shanghai-MAZ5(f,g)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区 F',
        value: 'cn-shanghai-f',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 1 可用区 B ',
        value: 'cn-qingdao-b',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太南部 1 可用区A',
        value: 'ap-south-1a',
    },
    {
        enable: 0,
        mav: false,
        text: '美西 1 可用区 B',
        value: 'us-west-1b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区F+可用区G）',
        value: 'cn-beijing-MAZ4(f,g)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区F+G+H）',
        value: 'cn-beijing-MAZ9(f,g,h)',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 F',
        value: 'cn-beijing-f',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太东南3 可用区A',
        value: 'ap-southeast-3a',
    },
    {
        enable: 0,
        mav: false,
        text: '日本 可用区A',
        value: 'ap-northeast-1a',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区1（可用区A + 可用区B）',
        value: 'us-east-1MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '美东 1 可用区 B',
        value: 'us-east-1b',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太东南3 可用区B',
        value: 'ap-southeast-3b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'ap-southeast-3MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '河源 可用区B',
        value: 'cn-heyuan-b',
    },
    {
        enable: 0,
        mav: false,
        text: '成都 可用区A',
        value: 'cn-chengdu-a',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'ap-south-1MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '亚太南部 1 可用区B',
        value: 'ap-south-1b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区1（可用区A + 可用区B）',
        value: 'us-west-1MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '美西 1 可用区 A',
        value: 'us-west-1a',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 5 可用区B',
        value: 'cn-huhehaote-b',
    },
    {
        enable: 0,
        mav: false,
        text: '新加坡可用区 A',
        value: 'ap-southeast-1a',
    },
    {
        enable: 0,
        mav: false,
        text: '日本 可用区B',
        value: 'ap-northeast-1b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'ap-northeast-1MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区C）',
        value: 'cn-zhangjiakou-MAZ2(b,c)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区3（可用区A+可用区B+可用区C）',
        value: 'cn-zhangjiakou-MAZ3(a,b,c)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区C）',
        value: 'cn-zhangjiakou-MAZ4(a,c)',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 3 可用区 C',
        value: 'cn-zhangjiakou-c',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'cn-huhehaote-MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 5 可用区A',
        value: 'cn-huhehaote-a',
    },
    {
        enable: 0,
        mav: false,
        text: '中东东部1 可用区A',
        value: 'me-east-1a',
    },
    {
        enable: 0,
        mav: false,
        text: '新加坡可用区 C',
        value: 'ap-southeast-1c',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区E+可用区F）',
        value: 'cn-shanghai-MAZ4(e,f)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区 E',
        value: 'cn-shanghai-e',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区E＋可用区F＋可用区G）',
        value: 'cn-shanghai-MAZ6(e,f,g)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'cn-heyuan-MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '河源 可用区A',
        value: 'cn-heyuan-a',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区9（可用区G+可用区H）',
        value: 'cn-hangzhou-MAZ9(g,h)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 1 可用区 B',
        value: 'cn-hangzhou-b',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 1 可用区 G',
        value: 'cn-hangzhou-g',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区C+可用区D）',
        value: 'cn-shenzhen-MAZ4(c,d)',
    },
    {
        enable: 0,
        mav: false,
        text: '华南 1 可用区 C',
        value: 'cn-shenzhen-c',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'eu-west-1MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '伦敦 可用区 A',
        value: 'eu-west-1a',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区8（可用区F+可用区G）',
        value: 'cn-hangzhou-MAZ8(f,g)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 1 可用区 D',
        value: 'cn-hangzhou-d',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 1 可用区 E',
        value: 'cn-hangzhou-e',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区F）',
        value: 'cn-hangzhou-MAZ6(b,f)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 1 可用区 F',
        value: 'cn-hangzhou-f',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区E+可用区F）',
        value: 'cn-hangzhou-MAZ5(b,e,f)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区D+可用区F）',
        value: 'cn-hangzhou-MAZ4(b,d,f)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区H',
        value: 'cn-shanghai-h',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区I',
        value: 'cn-shanghai-i',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区 A',
        value: 'cn-shanghai-a',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区 B',
        value: 'cn-shanghai-b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区C）',
        value: 'cn-shanghai-MAZ1(b,c)',
    },
    {
        enable: 0,
        mav: false,
        text: '华东 2 可用区 D',
        value: 'cn-shanghai-d',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区D）',
        value: 'cn-shanghai-MAZ2(b,d)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B+可用区D）',
        value: 'cn-shanghai-MAZ3(a,b,d)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区C+可用区E）',
        value: 'cn-beijing-MAZ3(c,e)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区C）',
        value: 'cn-beijing-MAZ5(a,c)',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 A',
        value: 'cn-beijing-a',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 B',
        value: 'cn-beijing-b',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 C',
        value: 'cn-beijing-c',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 D',
        value: 'cn-beijing-d',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区C+可用区D）',
        value: 'cn-beijing-MAZ2(a,c,d)',
    },
    {
        enable: 0,
        mav: false,
        text: '华北 2 可用区 E',
        value: 'cn-beijing-e',
    },
    {
        enable: 0,
        mav: false,
        text: '华南 1 可用区 B',
        value: 'cn-shenzhen-b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'cn-shenzhen-MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区C）',
        value: 'cn-shenzhen-MAZ2(b,c)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B+可用区C）',
        value: 'cn-shenzhen-MAZ3(a,b,c)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'cn-chengdu-MAZ1(a,b)',
    },
    {
        enable: 0,
        mav: false,
        text: '成都 可用区B',
        value: 'cn-chengdu-b',
    },
    {
        enable: 0,
        mav: false,
        text: '香港可用区C',
        value: 'cn-hongkong-c',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区C）',
        value: 'cn-hongkong-MAZ1(b,c)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区B+可用区C）',
        value: 'ap-southeast-1MAZ2(b,c)',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B+可用区C）',
        value: 'ap-southeast-1MAZ3(a,b,c)',
    },
    {
        enable: 0,
        mav: false,
        text: '新加坡可用区 B',
        value: 'ap-southeast-1b',
    },
    {
        enable: 0,
        mav: true,
        text: '多可用区（可用区A+可用区B）',
        value: 'ap-southeast-1MAZ1(a,b)',
    },
];

export default zoneId;
